### ISSUE TITLE
Fix lag sidebar after click 'Đơn đặt hàng' or 'Yêu cầu' in 'Hồ sơ của tôi'

### ISSUE THREAD

**Issue by thaitrinh2701** [TrinhCongThai-SE183743/SWP391-Luxuria#1]
![Screenshot 2024-06-30 012531](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/7b6e6aed-f9a5-4d1a-af28-f5633ac71a4f)

'Thông tin của tôi' section works well, but the other section lag when I access them. This issue affects all roles have both of these section.

**Comment by PhamNguyenVu-SE184101** [comment]
Found where the problem is, on my way to fix it
