### ISSUE TITLE
Typo error at "Gia công" page

### ISSUE THREAD

**Issue by thaitrinh2701** [TrinhCongThai-SE183743/SWP391-Luxuria#10]
![image](https://github.com/user-attachments/assets/e1319bf3-2bac-4144-ad32-c71211f3e892)
 
There is an error of a redundant colon in the line of "Sản phẩm phức tạp : : 10 - 15 ngày" 
It should be "Sản phẩm phức tạp : 10 - 15 ngày"

**Comment by PhamNguyenVu-SE184101** [comment]
Fixed in commit e530932
