### ISSUE TITLE
Fix components and adjust button when Dark mode is on

### ISSUE THREAD

**Issue by thaitrinh2701** [TrinhCongThai-SE183743/SWP391-Luxuria#2]
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/93c31eac-bb7f-4217-b5fd-f6a438e770b2)
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/8f60f036-3c38-47a5-b178-51a51e82a943)
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/c3216ee8-5d28-42c2-9320-89f85558a5d0)
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/30c2c374-ce75-421a-8a71-f4b3d1ad4ba3)
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/8c303969-f03e-4962-83c3-9d5cf9bb0794)

Some components appear visually broken when dark mode is enabled. Additionally, I believe some buttons could be redesigned to look better in dark mode.

**Comment by thaitrinh2701** [comment]
There may be additional dark mode bugs that I haven't encountered yet. DM me if you need any further adjustments or discover any other dark mode bugs.

**Comment by PhamNguyenVu-SE184101** [comment]
working on it

**Comment by PhamNguyenVu-SE184101** [comment]
Components and texts fixed in commit: 842b68d

**Comment by PhamNguyenVu-SE184101** [comment]
Images in Feature fixed in commit: 9a0b3c9
