### ISSUE TITLE
Data received error on admin page, 403 forbidden

### ISSUE THREAD

**Issue by thaitrinh2701** [TrinhCongThai-SE183743/SWP391-Luxuria#3]
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/759891f1-61e6-4fc2-b9ff-379fc21ba3cb)

**Comment by thaitrinh2701** [comment]
maybe fetching wrong API on frontend, I've tested on backend and functioning correctly.

**Comment by nhatlongg11** [comment]
Found where the problem is, the issue is fixed
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/143706489/9871e781-ed0e-49fa-8a56-273c21964895)
