### ISSUE TITLE
Footer problem in Production Staff Page

### ISSUE THREAD

**Issue by thaitrinh2701** [TrinhCongThai-SE183743/SWP391-Luxuria#5]
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/f8ef3df6-f538-496f-b921-9140071e6ae3)

**Comment by thaitrinh2701** [comment]
Other roles maybe encounter same issue, check again please

**Comment by nhatlongg11** [comment]
The problem is fixed!
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/143706489/fadf702f-2ed0-4531-aee2-00888889ac7f)
