### ISSUE TITLE
Error reupload images for products staff after customer denied

### ISSUE THREAD

**Issue by thaitrinh2701** [TrinhCongThai-SE183743/SWP391-Luxuria#6]
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/c8925a6e-dff6-4337-831d-94ac7da52835)

I'm trying to fix the bug in commit (1) 1e7dddb5b801f82b489b2d685f8edab1558ccbc4 and (2) e9b16b138a4ac0f8b035f7e311a292793ce61dbb; But it didn't work

**Comment by thaitrinh2701** [comment]
@LeVuDucLuong-SE183775  I really don't know what the issue is

**Comment by LeVuDucLuong-SE183775** [comment]
Fixed: Fix @Transactional issue

**Comment by thaitrinh2701** [comment]
@LeVuDucLuong-SE183775  new commit made the website can't connect, check again your latest commit, i had already revert to old commit and the website was normally function

**Comment by LeVuDucLuong-SE183775** [comment]
Fixed
