### ISSUE TITLE
Icons overlapping each other on the Admin page

### ISSUE THREAD

**Issue by thaitrinh2701** [TrinhCongThai-SE183743/SWP391-Luxuria#7]
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/c603933c-8171-4a2c-8ce7-1bfe2c24c0f8)

Sidebar looks kinda broken

**Comment by nhatlongg11** [comment]
The problem is fixed!
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/143706489/622cdbe8-e2f2-49c6-98c3-1d2e7567702a)
