### ISSUE TITLE
Error at Admin Page

### ISSUE THREAD

**Issue by thaitrinh2701** [TrinhCongThai-SE183743/SWP391-Luxuria#8]
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/169908472/f2a90d31-40c6-45f5-b579-7d303c8e5aca)

**Comment by nhatlongg11** [comment]
The problem is fixed!
Commit code: e0d9e6220d5d88a12a0f05a3c067bb162ab89f42
