### ISSUE TITLE
Cannot delete user because I got error 403

### ISSUE THREAD

**Issue by nhatlongg11** [TrinhCongThai-SE183743/SWP391-Luxuria#9]
I can't delete the chosen user because of the 403 error although I put it correct token, please give it a check and respond to me ASAP
![image](https://github.com/TrinhCongThai-SE183743/SWP391-Luxuria/assets/143706489/db387a64-028a-4068-bae6-43b4b5432f73)

**Comment by LeVuDucLuong-SE183775** [comment]
Fixed
